type User {
  id: ID
  email: String
  password: String
  secretKey: String
}

type CreateUserResponse {
  user: User
  success: Boolean!
  message: String!
}

type loginResponse {
  token: String
  user: User
  success: Boolean!
  message: String!
}

type Query {
  user(id: ID!): User!
  users: [User!]!
}

input UserInput {
  email: String!
  password: String!
}

type Mutation {
  registerUser(email: String!, password: String): CreateUserResponse!
  login(email: String!, password: String!): loginResponse!
}

